import{a as w,S as q,i as l}from"./assets/vendor-Rdv7LHNr.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const v="https://pixabay.com/api/",E="46861005-d1ea17891df84db160fa13612",S=15;async function P(t,o=1){const n={key:E,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:S,page:o};try{return(await w.get(v,{params:n})).data}catch(s){throw console.error("Error fetching images:",s),s}}const u=document.querySelector(".gallery"),m=document.querySelector(".more-btn");let R=new q(".gallery a");function $(){m.style.display="block"}function c(){m.style.display="none"}function B(t){const o=t.map(({webformatURL:n,largeImageURL:s,tags:e,likes:r,views:i,comments:b,downloads:L})=>`
  <li class="image-card">
        <a href="${s}">
        <img src="${n}" alt="${e}">
        </a>
        <div class="image-info">
                <p> Likes ${r}</p>
                <p> Comments ${b}</p>
                <p> Views ${i}</p>
                <p> Downloads ${L}</p>
</div>
        </li>`).join("");u.insertAdjacentHTML("beforeend",o),R.refresh()}function f(){u.innerHTML=""}function O(){const{height:t}=u.firstElementChild.getBoundingClientRect();window.scrollBy({top:t,behavior:"smooth"})}const _=document.querySelector(".form"),h=document.querySelector(".loader"),x=document.querySelector(".more-btn");let g="",a=1,p=0,A=15;c();function d(){h.style.display="flex"}function H(){h.style.display="none"}async function y(){try{d();const t=await P(g,a);if(p=t.totalHits,t.hits.length===0&&a===1){l.info({message:"Sorry, has no images for your request",position:"topRight"}),c();return}B(t.hits),a*A>=p?(c(),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):$(),O()}catch(t){l.error({title:"Error",message:t.message,position:"topRight"})}finally{H()}}_.addEventListener("submit",t=>{t.preventDefault();const o=t.currentTarget.elements.searchRequest.value.trim();if(!o){l.warning({message:"Please enter a valid search term.",position:"topRight"}),f(),c();return}g=o,a=1,f(),c(),d(),y()});x.addEventListener("click",()=>{a+=1,d(),y()});
//# sourceMappingURL=index.js.map
